In [148]:
# import uproot
import uproot3
from glob import glob
import json 
import os
from tqdm import tqdm
import numpy as np
import pandas as pd

In [149]:
pi0_dir = '/clusterfs/ml4hep/mpettee/ml4pions/data/user.angerami.mc16_13TeV.900246.PG_singlepi0_logE0p2to2000.e8312_e7400_s3170_r12383.v01-45-gaa27bcb_OutputStream/'
pion_dir = '/clusterfs/ml4hep/mpettee/ml4pions/data/user.angerami.mc16_13TeV.900247.PG_singlepion_logE0p2to2000.e8312_e7400_s3170_r12383.v01-45-gaa27bcb_OutputStream/'
pi0_files = sorted(glob(pi0_dir+"*.root"))
pion_files = sorted(glob(pion_dir+"*.root"))

In [150]:
# use a pared-down list of variables 
variables = ['cluster_cell_E', 'cluster_cell_ID',
             'trackPt','trackD0','trackZ0',
             'trackEta_EMB2','trackPhi_EMB2',         
             'nCluster','nTrack','truthPartE',
             'cluster_ENG_CALIB_TOT','cluster_E','cluster_Eta','cluster_Phi']
# variables = [var for var in a.keys()] # or use all columns available

In [151]:
def apply_cuts(arrays):
    df = pd.DataFrame.from_dict(arrays)
    return df

In [176]:
df = pd.DataFrame(a)
df = df[(df.nCluster == 1) & (df.nTrack == 1)]

In [179]:
df[["cluster_cell_E","cluster_E", "cluster_ENG_CALIB_TOT"]]

cluster_cell_E     cluster_E  \
186    ((3.229976, 1.1608506, 0.31251284, 0.20870583,...   [18.404346]   
251    ((67.45805, 67.27936, 6.9179206, 4.397215, 10....   [287.27362]   
257    ((20.431328, 17.754513, 0.86780506, 2.2994525,...   [73.489815]   
271    ((23.12278, 6.2180114, 7.8163133, 8.618049, 1....  [113.307236]   
430    ((39.235214, 1.7881701, 36.438137, 5.0182095, ...   [143.79388]   
...                                                  ...           ...   
19875  ((65.15955, 5.5585065, 46.775993, 7.837587, 5....   [234.04332]   
19894  ((30.677155, 6.8495717, 9.630726, 16.852072, 2...   [127.25384]   
19900  ((0.8555884, 0.4816065, 0.47336468, 0.3225594,...   [3.1514075]   
19913  ((12.766103, 4.6781993, 1.5169557, 7.9123487, ...    [91.83858]   
19967  ((268.6422, 36.675907, 43.22669, 51.853497, 8....   [653.50226]   

      cluster_ENG_CALIB_TOT  
186             [14.591501]  
251             [286.37073]  
257              [69.70105]  
271             [104.66714]  
430              [141.2497]  
...                     ...  
19875           [228.61777]  
19894           [125.44079]  
19900           [3.3217955]  
19913           [89.117195]  
19967           [648.51294]  

[304 rows x 3 columns]

In [169]:
df["track_dR"] = df.trackEta_EMB2**2 + df.trackPhi_EMB2**2

In [160]:
df["track_dR"] = np.sqrt(df.trackEta_EMB2**2 + df.trackPhi_EMB2**2)

TypeError: loop of ufunc does not support argument 0 of type numpy.ndarray which has no callable sqrt method

In [147]:
for file in pi0_files[:1]:
    prefix = file.split("/")[:-2]
    number = file.split("000")[-1][:-5]
    folder = os.path.join("/".join(prefix), "pi0_files_reduced")
    os.makedirs(folder, exist_ok=True)
    npy_filename = os.path.join(folder, str(number)+".npy")
    a = uproot.open(file)["EventTree"].arrays(variables, library = "np")
    df = apply_cuts(a)
#     np.save(npy_filename, a) 
#     print("Saved as {}.".format(npy_filename))

In [124]:
for file in pion_files[:10]:
    prefix = file.split("/")[:-2]
    number = file.split("000")[-1][:-5]
    folder = os.path.join("/".join(prefix), "pion_files_reduced")
    os.makedirs(folder, exist_ok=True)
    npy_filename = os.path.join(folder, str(number)+".npy")
    a = uproot.open(file)["EventTree"].arrays(variables, library = "np")
    np.save(npy_filename, a) 
    print("Saved as {}.".format(npy_filename))

Saved as /clusterfs/ml4hep/mpettee/ml4pions/data/pion_files_reduced/001.npy.
Saved as /clusterfs/ml4hep/mpettee/ml4pions/data/pion_files_reduced/002.npy.
Saved as /clusterfs/ml4hep/mpettee/ml4pions/data/pion_files_reduced/003.npy.
Saved as /clusterfs/ml4hep/mpettee/ml4pions/data/pion_files_reduced/004.npy.
Saved as /clusterfs/ml4hep/mpettee/ml4pions/data/pion_files_reduced/005.npy.
Saved as /clusterfs/ml4hep/mpettee/ml4pions/data/pion_files_reduced/006.npy.
Saved as /clusterfs/ml4hep/mpettee/ml4pions/data/pion_files_reduced/007.npy.
Saved as /clusterfs/ml4hep/mpettee/ml4pions/data/pion_files_reduced/008.npy.
Saved as /clusterfs/ml4hep/mpettee/ml4pions/data/pion_files_reduced/009.npy.
Saved as /clusterfs/ml4hep/mpettee/ml4pions/data/pion_files_reduced/010.npy.


# Scratch work

In [46]:
# uproot.open(pi0_dir+"user.angerami.24559740.OutputStream._000011.root")["CellGeo"].keys()

In [145]:
a = uproot.open(pi0_dir+"user.angerami.24559740.OutputStream._000011.root")["EventTree"].arrays(library = "np")

In [146]:
[var for var in a.keys()]

['runNumber',
 'eventNumber',
 'lumiBlock',
 'coreFlags',
 'mcEventNumber',
 'mcChannelNumber',
 'mcEventWeight',
 'nTruthPart',
 'G4PreCalo_n_EM',
 'G4PreCalo_E_EM',
 'G4PreCalo_n_Had',
 'G4PreCalo_E_Had',
 'truthVertexX',
 'truthVertexY',
 'truthVertexZ',
 'truthPartPdgId',
 'truthPartStatus',
 'truthPartBarcode',
 'truthPartPt',
 'truthPartE',
 'truthPartMass',
 'truthPartEta',
 'truthPartPhi',
 'nTrack',
 'trackPt',
 'trackP',
 'trackMass',
 'trackEta',
 'trackPhi',
 'trackNumberOfPixelHits',
 'trackNumberOfSCTHits',
 'trackNumberOfPixelDeadSensors',
 'trackNumberOfSCTDeadSensors',
 'trackNumberOfPixelSharedHits',
 'trackNumberOfSCTSharedHits',
 'trackNumberOfPixelHoles',
 'trackNumberOfSCTHoles',
 'trackNumberOfInnermostPixelLayerHits',
 'trackNumberOfNextToInnermostPixelLayerHits',
 'trackExpectInnermostPixelLayerHit',
 'trackExpectNextToInnermostPixelLayerHit',
 'trackNumberOfTRTHits',
 'trackNumberOfTRTOutliers',
 'trackChiSquared',
 'trackNumberDOF',
 'trackD0',
 'trackZ0',
 '

In [61]:
# a

In [47]:
np.save("/clusterfs/ml4hep/mpettee/ml4pions/data/pi0_files/011.npy", a) 

In [48]:
np.load("/clusterfs/ml4hep/mpettee/ml4pions/data/pi0_files/011.npy", allow_pickle=True).item()["cluster_E"]

array([array([], dtype=float32), array([224.24033], dtype=float32),
       array([1007.15283], dtype=float32), ...,
       array([79.58574], dtype=float32),
       array([148.06265  ,   0.2166447], dtype=float32),
       array([5.27755  , 2.2608376], dtype=float32)], dtype=object)

In [20]:
file = uproot3.recreate("test.root")
file["tree"] = uproot3.newtree({"branch1": np.int32, 
                               "branch2": np.float})
file["tree"].extend({"branch1": [1,3,5], "branch2": [2,4,6],})
file.close()

In [24]:
uproot.open("test.root")["tree"].show()

name                 | typename                 | interpretation                
---------------------+--------------------------+-------------------------------
branch1              | int32_t                  | AsDtype('>i4')
branch2              | double                   | AsDtype('>f8')


In [26]:
uproot.open("test.root")["tree"]["branch1"].array()

<Array [1, 3, 5] type='3 * int32'>

# Pi0 files

In [69]:
jsonString = json.dumps(pi0_files[:400])
jsonFile = open("pi0_training_data.json", "w")
jsonFile.write(jsonString)
jsonFile.close()

jsonString = json.dumps(pi0_files[400:])
jsonFile = open("pi0_validation_data.json", "w")
jsonFile.write(jsonString)
jsonFile.close()

In [72]:
total_clusters = 0 

for file in pi0_files[:400]:
    total_clusters += uproot.open(file)["EventTree"].arrays(["nCluster"], 
                                                            library = "pd").sum()
print("Pi0 training",total_clusters)  

total_clusters = 0 

for file in pi0_files[400:]:
    total_clusters += uproot.open(file)["EventTree"].arrays(["nCluster"], 
                                                            library = "pd").sum()
print("Pi0 validation",total_clusters)    

Pi0 training nCluster    8422068
dtype: int64
Pi0 validation nCluster    2105683
dtype: int64


# Pion files

In [71]:
jsonString = json.dumps(pion_files[:400])
jsonFile = open("pion_training_data.json", "w")
jsonFile.write(jsonString)
jsonFile.close()

jsonString = json.dumps(pion_files[400:])
jsonFile = open("pion_validation_data.json", "w")
jsonFile.write(jsonString)
jsonFile.close()

In [73]:
total_clusters = 0 

for file in pion_files[:400]:
    total_clusters += uproot.open(file)["EventTree"].arrays(["nCluster"], 
                                                            library = "pd").sum()
print("Pion training",total_clusters)  

total_clusters = 0 

for file in pion_files[400:]:
    total_clusters += uproot.open(file)["EventTree"].arrays(["nCluster"], 
                                                            library = "pd").sum()
print("Pion validation",total_clusters)    

Pion training nCluster    14938923
dtype: int64
Pion validation nCluster    3729929
dtype: int64


# Experiment with adding cuts

In [35]:
df = uproot.open(pion_dir+"user.angerami.24559744.OutputStream._000001.root")["EventTree"].arrays(
    library= "pd", entry_stop=10)

In [27]:
df[0].shape

(10, 29)

In [28]:
df[1].shape

(27, 86)

In [34]:
df[0].keys()

Index(['runNumber', 'eventNumber', 'lumiBlock', 'coreFlags', 'mcEventNumber',
       'mcChannelNumber', 'mcEventWeight', 'nTruthPart', 'G4PreCalo_n_EM',
       'G4PreCalo_E_EM', 'G4PreCalo_n_Had', 'G4PreCalo_E_Had', 'truthVertexX',
       'truthVertexY', 'truthVertexZ', 'truthPartPdgId', 'truthPartStatus',
       'truthPartBarcode', 'truthPartPt', 'truthPartE', 'truthPartMass',
       'truthPartEta', 'truthPartPhi', 'nTrack', 'nCluster', 'cluster_cell_ID',
       'cluster_cell_E', 'cluster_hitsTruthIndex', 'cluster_hitsTruthE'],
      dtype='object')

In [37]:
df[0][["nCluster","nTrack"]]

nCluster  nTrack
entry subentry                  
0     0                0       1
1     0                1       1
2     0                0       0
3     0                1       0
4     0                2       1
5     0                0       1
6     0                3       1
7     0               22      21
8     0                2       1
9     0                0       0

In [38]:
df2 = df[0].loc[df[0].nCluster > 0]

In [42]:
df2

runNumber  eventNumber  lumiBlock  coreFlags  mcEventNumber  \
entry subentry                                                                
1     0            284500        25982          1          0          25982   
3     0            284500        25649          1          0          25649   
4     0            284500        25589          1          0          25589   
6     0            284500        26257          1          0          26257   
7     0            284500        25100          1          0          25100   
8     0            284500        26499          1          0          26499   

                mcChannelNumber  mcEventWeight  nTruthPart  G4PreCalo_n_EM  \
entry subentry                                                               
1     0                  900247            1.0           1               0   
3     0                  900247            1.0           1               0   
4     0                  900247            1.0           1               0   
6     0                  900247            1.0           1               0   
7     0                  900247            1.0           1              81   
8     0                  900247            1.0           1               0   

                G4PreCalo_E_EM  ...   truthPartE  truthPartMass  truthPartEta  \
entry subentry                  ...                                             
1     0               0.000000  ...   718.672852           0.14     -0.047595   
3     0               0.000000  ...   344.893341           0.14     -2.835764   
4     0               0.000000  ...     6.982437           0.14      0.250744   
6     0               0.000000  ...   624.100647           0.14     -1.919238   
7     0             373.205017  ...  1267.736694           0.14     -1.752635   
8     0               0.000000  ...    50.317371           0.14     -0.850443   

                truthPartPhi  nTrack  nCluster  \
entry subentry                                   
1     0             0.052207       1         1   
3     0            -0.595305       0         1   
4     0            -0.004713       1         2   
6     0             2.418441       1         3   
7     0             1.758621      21        22   
8     0            -0.479925       1         2   

                                                  cluster_cell_ID  \
entry subentry                                                      
1     0         ((1140850704, 1141882896, 1140867088, 11408509...   
3     0         ((740296306, 740296304, 740296308, 740295794, ...   
4     0         ((767562746, 767562744, 767562748, 767562234, ...   
6     0         ((751052484, 751052482, 751052486, 751051972, ...   
7     0         ((751048846, 751048844, 751048848, 751048334, ...   
8     0         ((759186902, 759186900, 759186904, 759186390, ...   

                                                   cluster_cell_E  \
entry subentry                                                      
1     0         ((421.69482, 7.1292477, 6.2763577, 13.232551, ...   
3     0         ((120.92174, 3.663723, 47.338703, 19.371336, 2...   
4     0         ((0.6589358, 0.46683934, 0.08905287, 0.0470919...   
6     0         ((51.25548, 14.139051, 3.7185004, 3.4223423, 1...   
7     0         ((159.84758, 25.522734, 44.841637, 10.064571, ...   
8     0         ((4.963051, 0.48994341, 1.8525301, 0.11810666,...   

                                           cluster_hitsTruthIndex  \
entry subentry                                                      
1     0                                                     ((0))   
3     0                                                     ((0))   
4     0                                                ((0), (0))   
6     0                                           ((0), (0), (0))   
7     0         ((0), (0), (0), (0), (0), (0), (0), (0), (0), ...   
8     0                                                ((0), (0))   

                                               cl

In [32]:
df[1]

runNumber  eventNumber  lumiBlock  coreFlags  mcEventNumber  \
entry subentry                                                                
0     0            284500        25555          1          0          25555   
1     0            284500        25982          1          0          25982   
4     0            284500        25589          1          0          25589   
5     0            284500        26538          1          0          26538   
6     0            284500        26257          1          0          26257   
7     0            284500        25100          1          0          25100   
      1            284500        25100          1          0          25100   
      2            284500        25100          1          0          25100   
      3            284500        25100          1          0          25100   
      4            284500        25100          1          0          25100   
      5            284500        25100          1          0          25100   
      6            284500        25100          1          0          25100   
      7            284500        25100          1          0          25100   
      8            284500        25100          1          0          25100   
      9            284500        25100          1          0          25100   
      10           284500        25100          1          0          25100   
      11           284500        25100          1          0          25100   
      12           284500        25100          1          0          25100   
      13           284500        25100          1          0          25100   
      14           284500        25100          1          0          25100   
      15           284500        25100          1          0          25100   
      16           284500        25100          1          0          25100   
      17           284500        25100          1          0          25100   
      18           284500        25100          1          0          25100   
      19           284500        25100          1          0          25100   
      20           284500        25100          1          0          25100   
8     0            284500        26499          1          0          26499   

                mcChannelNumber  mcEventWeight  nTruthPart  G4PreCalo_n_EM  \
entry subentry                                                               
0     0                  900247            1.0           1               0   
1     0                  900247            1.0           1               0   
4     0                  900247            1.0           1               0   
5     0                  900247            1.0           1               0   
6     0                  900247            1.0           1               0   
7     0                  900247            1.0           1              81   
      1                  900247            1.0           1              81   
      2                  900247            1.0           1              81   
      3                  900247            1.0           1              81   
      4                  900247            1.0           1              81   
      5                  900247            1.0           1              81   
      6                  900247            1.0           1              81   
      7                  900247            1.0           1              81   
      8                  900247            1.0           1              81   
      9                  900247            1.0           1              81   
      10                 900247            1.0           1              81   
      11                 900247            1.0           1              81   
      12                 900247            1.0           1              81   
      13                 900247            1.0           1              81   
      14                 900247            1.0           1              81   
      15