In [27]:
import numpy as np
import os
import sys
import glob
import uproot as ur
import matplotlib.pyplot as plt
import time
import seaborn as sns
import tensorflow as tf
from graph_nets import utils_np
from graph_nets import utils_tf
from graph_nets.graphs import GraphsTuple
import sonnet as snt
import argparse
import yaml
import logging
import tensorflow as tf
from tqdm import tqdm

from gn4pions.modules.data import GraphDataGenerator
from gn4pions.modules.models import MultiOutWeightedRegressModel
from gn4pions.modules.utils import convert_to_tuple

sns.set_context('poster')

In [2]:
# Loading model config
config_file = 'gn4pions/configs/test_ming.yaml' # for a quick run of the notebook
# config_file = 'gn4pions/configs/baseline.yaml' # for actual training
config = yaml.load(open(config_file), Loader=yaml.FullLoader)

# Data config
data_config = config['data']

data_dir = data_config['data_dir']
num_train_files = data_config['num_train_files']
num_val_files = data_config['num_val_files']
batch_size = data_config['batch_size']
shuffle = data_config['shuffle']
num_procs = data_config['num_procs']
preprocess = data_config['preprocess']
output_dir = data_config['output_dir']
already_preprocessed = data_config['already_preprocessed']  # Set to false when running training for first time

# Model Config
model_config = config['model']

concat_input = model_config['concat_input']


# Traning Config
train_config = config['training']

epochs = train_config['epochs']
learning_rate = train_config['learning_rate']
alpha = train_config['alpha']
os.environ['CUDA_VISIBLE_DEVICES'] = str(train_config['gpu'])
log_freq = train_config['log_freq']
save_dir = train_config['save_dir'] + config_file.replace('.yaml','').split('/')[-1] + '_' + time.strftime("%Y%m%d")

os.makedirs(save_dir, exist_ok=True)
yaml.dump(config, open(save_dir + '/config.yaml', 'w'))


In [ ]:
# Read data and create data generators

pi0_files = np.sort(glob.glob(data_dir+'*pi0*/*root'))
pion_files = np.sort(glob.glob(data_dir+'*pion*/*root'))

train_start = 0
train_end = train_start + num_train_files
val_end = train_end + num_val_files

pi0_train_files = pi0_files[train_start:train_end]
pi0_val_files = pi0_files[train_end:val_end]
pion_train_files = pion_files[train_start:train_end]
pion_val_files = pion_files[train_end:val_end]

train_output_dir = None
val_output_dir = None

# Get Data
if preprocess:
    train_output_dir = output_dir + 'train/'
    val_output_dir = output_dir + 'val/'

    if already_preprocessed:
        train_files = np.sort(glob.glob(train_output_dir+'*.p'))[:num_train_files]
        val_files = np.sort(glob.glob(val_output_dir+'*.p'))[:num_val_files]

        pi0_train_files = train_files
        pi0_val_files = val_files
        pion_train_files = None
        pion_val_files = None

        train_output_dir = None
        val_output_dir = None

# Traning Data Generator
# Will preprocess data if it doesnt find pickled files
data_gen_train = GraphDataGenerator(pi0_file_list=pi0_train_files,
                                    pion_file_list=pion_train_files,
                                    cellGeo_file=data_dir+'CellGeo.neighbours.root',
                                    batch_size=batch_size,
                                    shuffle=shuffle,
                                    num_procs=num_procs,
                                    preprocess=preprocess,
                                    output_dir=train_output_dir)

# Validation Data generator
# Will preprocess data if it doesnt find pickled files
data_gen_val = GraphDataGenerator(pi0_file_list=pi0_val_files,
                                  pion_file_list=pion_val_files,
                                  cellGeo_file=data_dir+'CellGeo.neighbours.root',
                                  batch_size=batch_size,
                                  shuffle=shuffle,
                                  num_procs=num_procs,
                                  preprocess=preprocess,
                                  output_dir=val_output_dir)



Preprocessing and saving data to /clusterfs/ml4hep/mfong/ML4Pions/graph_data_tracks/train/
Processing file number 0


In [17]:
# Get batch of data
def get_batch(data_iter):
    for graphs, targets in data_iter:
        graphs = convert_to_tuple(graphs)
        targets = tf.convert_to_tensor(targets)
        yield graphs, targets
        
# Define loss function        
mae_loss = tf.keras.losses.MeanAbsoluteError()
bce_loss = tf.keras.losses.BinaryCrossentropy(from_logits=True)
def loss_fn(targets, regress_preds, class_preds):
    regress_loss = mae_loss(targets[:,:1], regress_preds)
    class_loss = bce_loss(targets[:,1:], class_preds)
    combined_loss = alpha*regress_loss + (1 - alpha)*class_loss 
    return regress_loss, class_loss, combined_loss

In [18]:
# Get a sample graph for tf.function decorator
samp_graph, samp_target = next(get_batch(data_gen_train.generator()))
data_gen_train.kill_procs()
graph_spec = utils_tf.specs_from_graphs_tuple(samp_graph, True, True, True)

# Training set
@tf.function(input_signature=[graph_spec, tf.TensorSpec(shape=[None,2], dtype=tf.float32)])
def train_step(graphs, targets):
    with tf.GradientTape() as tape:
        regress_output, class_output = model(graphs)
        regress_preds = regress_output.globals
        class_preds = class_output.globals
        regress_loss, class_loss, loss = loss_fn(targets, regress_preds, class_preds)

    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    return regress_loss, class_loss, loss

# Validation Step
@tf.function(input_signature=[graph_spec, tf.TensorSpec(shape=[None,2], dtype=tf.float32)])
def val_step(graphs, targets):
    regress_output, class_output = model(graphs)
    regress_preds = regress_output.globals
    class_preds = class_output.globals
    regress_loss, class_loss, loss = loss_fn(targets, regress_preds, class_preds)
    return regress_loss, class_loss, loss, regress_preds, class_preds

In [21]:
samp_graph

GraphsTuple(nodes=<tf.Tensor: shape=(462539,), dtype=float32, numpy=
array([ 1.1165453 ,  0.21428572, -2.276295  , ...,  0.1426901 ,
       -1.4181322 ,  0.75448257], dtype=float32)>, edges=<tf.Tensor: shape=(199343, 10), dtype=float32, numpy=
array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)>, receivers=<tf.Tensor: shape=(206577,), dtype=int32, numpy=array([     1,      2,      3, ..., 462172, 462172, 462172], dtype=int32)>, senders=<tf.Tensor: shape=(206577,), dtype=int32, numpy=array([     0,      0,      0, ..., 462173, 462174, 462175], dtype=int32)>, globals=<tf.Tensor: shape=(1024, 1), dtype=float32, numpy=
array([[ 1.7332985 ],
       [ 1.9895272 ],
       [ 3.0432835 ],
       ...,
       [-0.08471473],
       [ 2.131969  ],
       [ 1.0343087 ]], dtype=float32)>, n_node=<tf.

In [22]:
# Model 
model = MultiOutWeightedRegressModel(global_output_size=1, num_outputs=2, model_config=model_config)

# Optimizer
optimizer = tf.keras.optimizers.Adam(learning_rate)

# Average epoch losses
training_loss_epoch = []
training_loss_regress_epoch = []
training_loss_class_epoch = []
val_loss_epoch = []
val_loss_regress_epoch = []
val_loss_class_epoch = []

# Model checkpointing, load latest model if available
checkpoint = tf.train.Checkpoint(module=model)
checkpoint_prefix = os.path.join(save_dir, 'latest_model')
latest = tf.train.latest_checkpoint(save_dir)
if latest is not None:
    checkpoint.restore(latest)
else:
    checkpoint.save(checkpoint_prefix)

In [23]:
# for i, (graph_data_tr, targets_tr) in enumerate(get_batch(data_gen_train.generator())):
#     print("Targets: ",targets_tr[:,0])

In [24]:
# Run training
curr_loss = 1e5

for e in range(epochs):

    print(f'\n\nStarting epoch: {e}')
    epoch_start = time.time()
    
    # Batchwise losses
    training_loss = []
    training_loss_regress = []
    training_loss_class = []
    val_loss = []
    val_loss_regress = []
    val_loss_class = []

    # Train
    print('Training...')
    start = time.time()
    for i, (graph_data_tr, targets_tr) in enumerate(get_batch(data_gen_train.generator())):
        losses_tr_rg, losses_tr_cl, losses_tr = train_step(graph_data_tr, targets_tr)

        training_loss.append(losses_tr.numpy())
        training_loss_regress.append(losses_tr_rg.numpy())
        training_loss_class.append(losses_tr_cl.numpy())

        if not (i-1)%log_freq:
            end = time.time()
            print(f'Iter: {i:04d}, ', end='')
            print(f'Tr_loss_mean: {np.mean(training_loss):.4f}, ', end='')
            print(f'Tr_loss_rg_mean: {np.mean(training_loss_regress):.4f}, ', end='') 
            print(f'Tr_loss_cl_mean: {np.mean(training_loss_class):.4f}, ', end='') 
            print(f'Took {end-start:.4f}secs')
            start = time.time()
                  
    training_loss_epoch.append(training_loss)
    training_loss_regress_epoch.append(training_loss_regress)
    training_loss_class_epoch.append(training_loss_class)
    training_end = time.time()

    # validate
    print('\nValidation...')
    all_targets = []
    all_outputs = []
    all_energies = []
    start = time.time()
    for i, (graph_data_val, targets_val) in enumerate(get_batch(data_gen_val.generator())):
        losses_val_rg, losses_val_cl, losses_val, regress_vals, class_vals = val_step(graph_data_val, targets_val)

        targets_val = targets_val.numpy()
        regress_vals = regress_vals.numpy()
        class_vals = class_vals.numpy()

        targets_val[:,0] = 10**targets_val[:,0]
        regress_vals = 10**regress_vals
        class_vals =  tf.math.sigmoid(class_vals)

        output_vals = np.hstack([regress_vals, class_vals])

        val_loss.append(losses_val.numpy())
        val_loss_regress.append(losses_val_rg.numpy())
        val_loss_class.append(losses_val_cl.numpy())

        all_targets.append(targets_val)
        all_outputs.append(output_vals)

        if not (i-1)%log_freq:
            end = time.time()
            print(f'Iter: {i:04d}, ', end='')
            print(f'Val_loss_mean: {np.mean(val_loss):.4f}, ', end='')
            print(f'Val_loss_rg_mean: {np.mean(val_loss_regress):.4f}, ', end='') 
            print(f'Val_loss_cl_mean: {np.mean(val_loss_class):.4f}, ', end='') 
            print(f'Took {end-start:.4f}secs')
            start = time.time()

    epoch_end = time.time()

    all_targets = np.concatenate(all_targets)
    all_outputs = np.concatenate(all_outputs)

    val_loss_epoch.append(val_loss)
    val_loss_regress_epoch.append(val_loss_regress)
    val_loss_class_epoch.append(val_loss_class)

    
    # Book keeping
    val_mins = int((epoch_end - training_end)/60)
    val_secs = int((epoch_end - training_end)%60)
    training_mins = int((training_end - epoch_start)/60)
    training_secs = int((training_end - epoch_start)%60)
    print(f'\nEpoch {e} ended')
    print(f'Training: {training_mins:2d}:{training_secs:02d}')
    print(f'Validation: {val_mins:2d}:{val_secs:02d}')
    
    
    # Save losses
    np.savez(save_dir+'/losses', 
            training=training_loss_epoch, validation=val_loss_epoch,
            training_regress=training_loss_regress_epoch, validation_regress=val_loss_regress_epoch,
            training_class=training_loss_class_epoch, validation_class=val_loss_class_epoch,
            )

    
    # Checkpoint if validation loss improved
    if np.mean(val_loss)<curr_loss:
        print(f'Loss decreased from {curr_loss:.4f} to {np.mean(val_loss):.4f}')
        print(f'Checkpointing and saving predictions to:\n{save_dir}')
        curr_loss = np.mean(val_loss)
        np.savez(save_dir+'/predictions', 
                targets=all_targets, 
                outputs=all_outputs,
                energies=all_energies)
        checkpoint.save(checkpoint_prefix)
    else: 
        print(f'Loss didnt decrease from {curr_loss:.4f}')
    
    
    # Decrease learning rate every few epochs
    if not (e+1)%2:   #%20:
        optimizer.learning_rate = optimizer.learning_rate/10
        print(f'Learning rate decreased to: {optimizer.learning_rate.value():.3e}')



Starting epoch: 0
Training...


ValueError: in user code:

    /tmp/ipykernel_4297/2872865351.py:10 train_step  *
        regress_output, class_output = model(graphs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/utils.py:171 _decorate_unbound_method  *
        return decorator_fn(bound_method, self, args, kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/base.py:272 wrap_with_name_scope  *
        return method(*args, **kwargs)
    /global/home/users/mfong/git/gn4pions_eastbay/gn4pions/modules/models.py:169 __call__  *
        latent = self._core[0](input_op)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/utils.py:171 _decorate_unbound_method  *
        return decorator_fn(bound_method, self, args, kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/base.py:272 wrap_with_name_scope  *
        return method(*args, **kwargs)
    /global/home/users/mfong/git/gn4pions_eastbay/gn4pions/modules/models.py:99 __call__  *
        return self._network(inputs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/utils.py:171 _decorate_unbound_method  *
        return decorator_fn(bound_method, self, args, kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/base.py:272 wrap_with_name_scope  *
        return method(*args, **kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/utils.py:171 _decorate_unbound_method  *
        return decorator_fn(bound_method, self, args, kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/base.py:272 wrap_with_name_scope  *
        return method(*args, **kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/graph_nets/_base.py:78 __call__  *
        return self._build(*args, **kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/utils.py:171 _decorate_unbound_method  *
        return decorator_fn(bound_method, self, args, kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/base.py:272 wrap_with_name_scope  *
        return method(*args, **kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/graph_nets/modules.py:301 _build  *
        return self._global_block(self._node_block(self._edge_block(graph)))
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/utils.py:171 _decorate_unbound_method  *
        return decorator_fn(bound_method, self, args, kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/base.py:272 wrap_with_name_scope  *
        return method(*args, **kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/utils.py:171 _decorate_unbound_method  *
        return decorator_fn(bound_method, self, args, kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/base.py:272 wrap_with_name_scope  *
        return method(*args, **kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/graph_nets/_base.py:78 __call__  *
        return self._build(*args, **kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/utils.py:171 _decorate_unbound_method  *
        return decorator_fn(bound_method, self, args, kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/sonnet/src/base.py:272 wrap_with_name_scope  *
        return method(*args, **kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/graph_nets/blocks.py:458 _build  *
        collected_edges = tf.concat(edges_to_collect, axis=-1)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:206 wrapper  **
        return target(*args, **kwargs)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py:1769 concat
        return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/tensorflow/python/ops/gen_array_ops.py:1227 concat_v2
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py:748 _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py:599 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:3561 _create_op_internal
        ret = Operation(
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:2041 __init__
        self._c_op = _create_c_op(self._graph, node_def, inputs,
    /global/home/users/mfong/anaconda3/envs/gn4pions/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:1883 _create_c_op
        raise ValueError(str(e))

    ValueError: Shape must be rank 2 but is rank 1 for '{{node MultiOutWeightedRegressModel/core_0/graph_network/edge_block/concat}} = ConcatV2[N=4, T=DT_FLOAT, Tidx=DT_INT32](graphs_1, MultiOutWeightedRegressModel/core_0/graph_network/edge_block/broadcast_receiver_nodes_to_edges/GatherV2, MultiOutWeightedRegressModel/core_0/graph_network/edge_block/broadcast_sender_nodes_to_edges/GatherV2, MultiOutWeightedRegressModel/core_0/graph_network/edge_block/broadcast_globals_to_edges/repeat/boolean_mask/GatherV2, MultiOutWeightedRegressModel/core_0/graph_network/edge_block/concat/axis)' with input shapes: [?,10], [?], [?], [?,1], [].


In [25]:
graph_data_tr

GraphsTuple(nodes=<tf.Tensor: shape=(462539,), dtype=float32, numpy=
array([ 1.1165453 ,  0.21428572, -2.276295  , ...,  0.1426901 ,
       -1.4181322 ,  0.75448257], dtype=float32)>, edges=<tf.Tensor: shape=(199343, 10), dtype=float32, numpy=
array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)>, receivers=<tf.Tensor: shape=(206577,), dtype=int32, numpy=array([     1,      2,      3, ..., 462172, 462172, 462172], dtype=int32)>, senders=<tf.Tensor: shape=(206577,), dtype=int32, numpy=array([     0,      0,      0, ..., 462173, 462174, 462175], dtype=int32)>, globals=<tf.Tensor: shape=(1024, 1), dtype=float32, numpy=
array([[ 1.7332985 ],
       [ 1.9895272 ],
       [ 3.0432835 ],
       ...,
       [-0.08471473],
       [ 2.131969  ],
       [ 1.0343087 ]], dtype=float32)>, n_node=<tf.

In [26]:
targets_tr

<tf.Tensor: shape=(1024, 2), dtype=float32, numpy=
array([[ 1.7235074 ,  0.        ],
       [ 2.057452  ,  1.        ],
       [ 3.0513353 ,  0.        ],
       ...,
       [-0.13555424,  1.        ],
       [ 2.1366858 ,  1.        ],
       [ 1.0670452 ,  1.        ]], dtype=float32)>